compressionLevel: mixed

nodeLinker: pnp

npmPublishAccess: public

yarnPath: .yarn/releases/yarn-4.0.0.cjs

packageExtensions:
  "rollup@*":
    dependencies:
      "@rollup/plugin-typescript": "*"
      "tslib": "*"
